name: Build Inspector Portable

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Récupération du code
      uses: actions/checkout@v4

    - name: Installation de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installation des outils
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller psutil

    - name: Compilation en Exécutable
      run: |
        # --icon="ico.ico" applique l'icône présente à côté de main.py
        # Le retrait de --uac-admin permet de lancer l'application sans privilèges initiaux
        pyinstaller --onefile --name="Inspector" --icon="ico.ico" main.py

    - name: Téléverser l'exécutable sur GitHub
      uses: actions/upload-artifact@v4
      with:
        name: Inspector-Windows
        path: dist/Inspector.exe
